// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXNjUPOXPO-so1Otl7uED-Cklts97db8',
    appId: '1:68058912781:web:cc66628240957574efdd44',
    messagingSenderId: '68058912781',
    projectId: 'chat-app-af8c5',
    authDomain: 'chat-app-af8c5.firebaseapp.com',
    storageBucket: 'chat-app-af8c5.appspot.com',
    measurementId: 'G-SCPKGBNH7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHsJVtD40GNfQLM2DtyXnL9dEPTl1uBTA',
    appId: '1:68058912781:android:50812cacf9d353efefdd44',
    messagingSenderId: '68058912781',
    projectId: 'chat-app-af8c5',
    storageBucket: 'chat-app-af8c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOeQPW81hSmg3IObxPN_CgC982faeNTSo',
    appId: '1:68058912781:ios:2379865460189202efdd44',
    messagingSenderId: '68058912781',
    projectId: 'chat-app-af8c5',
    storageBucket: 'chat-app-af8c5.appspot.com',
    iosClientId: '68058912781-kj8apqdmpvq6vc8i6sb9krcd8srt5vun.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOeQPW81hSmg3IObxPN_CgC982faeNTSo',
    appId: '1:68058912781:ios:2379865460189202efdd44',
    messagingSenderId: '68058912781',
    projectId: 'chat-app-af8c5',
    storageBucket: 'chat-app-af8c5.appspot.com',
    iosClientId: '68058912781-kj8apqdmpvq6vc8i6sb9krcd8srt5vun.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
